import type { IntakeFormTemplate } from "@/lib/stories-domain";

export const referenceIntakeTemplates: IntakeFormTemplate[] = [
  {
    id: "template_overview",
    name: "Program Overview Form",
    storyType: "OVERVIEW",
    description: "For administrators who can discuss the institution's history, current programs, and future plans.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "title", type: "text", label: "Title/Position", placeholder: "Your title or position", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      {
        id: "background",
        type: "textarea",
        label: "Your Background & Expertise",
        placeholder: "Please describe your background, years of experience, and connection to the institution's programs...",
        required: true,
      },
      {
        id: "history",
        type: "textarea",
        label: "Institution History",
        placeholder: "Share key milestones and background of your institution...",
        required: false,
      },
      {
        id: "currentPrograms",
        type: "textarea",
        label: "Current Programs & Offerings",
        placeholder: "Describe your current program offerings and what makes them special...",
        required: false,
      },
      {
        id: "futurePlans",
        type: "textarea",
        label: "Future Plans & Goals",
        placeholder: "What are your plans and goals for the future?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_esl",
    name: "ESL Student Success Form",
    storyType: "ESL",
    description: "For ESL students to share their learning journey and achievements.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      { id: "nativeLanguage", type: "text", label: "Native Language", placeholder: "What is your first language?", required: false },
      {
        id: "educationLevel",
        type: "select",
        label: "Education Level in Home Country",
        required: false,
        options: ["Elementary", "Some High School", "High School Graduate", "Some College", "College Graduate", "Graduate Degree"],
      },
      {
        id: "background",
        type: "textarea",
        label: "Your Story",
        placeholder: "Tell us about your journey - why you came to the U.S., why you decided to study ESL, your goals...",
        required: true,
      },
      {
        id: "challenges",
        type: "textarea",
        label: "Challenges Overcome",
        placeholder: "What challenges have you faced and how did the ESL program help you overcome them?",
        required: false,
      },
      {
        id: "achievements",
        type: "textarea",
        label: "Achievements & Progress",
        placeholder: "What are you most proud of? How has your English improved?",
        required: false,
      },
      {
        id: "goals",
        type: "textarea",
        label: "Future Goals",
        placeholder: "What are your goals now that you've improved your English?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_hsd_ged",
    name: "HSD/GED Graduate Success Form",
    storyType: "HSD_GED",
    description: "For high school diploma or GED graduates to share their educational journey.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      { id: "age", type: "text", label: "Age (Optional)", placeholder: "Your age", required: false },
      {
        id: "whyNow",
        type: "textarea",
        label: "Why pursue your diploma/GED now?",
        placeholder: "What motivated you to return to education?",
        required: true,
      },
      {
        id: "background",
        type: "textarea",
        label: "Your Educational Journey",
        placeholder: "Tell us about your path - why you left school originally, what brought you back, what the journey has been like...",
        required: true,
      },
      {
        id: "challenges",
        type: "textarea",
        label: "Challenges Overcome",
        placeholder: "What obstacles did you face and how did you overcome them?",
        required: false,
      },
      {
        id: "support",
        type: "textarea",
        label: "Program Support",
        placeholder: "How did the program support you in reaching your goal?",
        required: false,
      },
      {
        id: "nextSteps",
        type: "textarea",
        label: "Next Steps & Goals",
        placeholder: "What are your plans now that you have your diploma/GED?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_cte",
    name: "CTE Program Success Form",
    storyType: "CTE",
    description: "For Career Technical Education students to share their training and career path.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      {
        id: "program",
        type: "text",
        label: "CTE Program/Career Field",
        placeholder: "Which CTE program are you in? (e.g., Medical Assistant, HVAC, Welding)",
        required: true,
      },
      {
        id: "background",
        type: "textarea",
        label: "Your Story",
        placeholder: "Tell us why you chose this career field and what drew you to this program...",
        required: true,
      },
      {
        id: "training",
        type: "textarea",
        label: "Training Experience",
        placeholder: "What has your training experience been like? What skills have you gained?",
        required: false,
      },
      {
        id: "handson",
        type: "textarea",
        label: "Hands-On Experience",
        placeholder: "Tell us about any externships, hands-on training, or real-world experience...",
        required: false,
      },
      {
        id: "career",
        type: "textarea",
        label: "Career Plans",
        placeholder: "What are your career goals? Have you secured employment or plan to?",
        required: false,
      },
      {
        id: "advice",
        type: "textarea",
        label: "Advice for Others",
        placeholder: "What would you tell someone considering this career path?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_employer",
    name: "Employer Partnership Form",
    storyType: "EMPLOYER",
    description: "For employers who hire graduates or provide externships and training opportunities.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "title", type: "text", label: "Title/Position", placeholder: "Your title", required: true },
      { id: "company", type: "text", label: "Company Name", placeholder: "Your company or organization", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      {
        id: "partnership",
        type: "textarea",
        label: "Partnership with Institution",
        placeholder: "Describe your partnership - do you provide externships, hire graduates, collaborate on training?",
        required: true,
      },
      {
        id: "quality",
        type: "textarea",
        label: "Quality of Training",
        placeholder: "How would you describe the quality of training graduates receive? What impresses you?",
        required: true,
      },
      {
        id: "graduates",
        type: "textarea",
        label: "Working with Graduates",
        placeholder: "Tell us about your experience hiring or training graduates from this institution...",
        required: false,
      },
      {
        id: "value",
        type: "textarea",
        label: "Value to Your Business",
        placeholder: "How has this partnership benefited your business or organization?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_staff",
    name: "Faculty/Staff Success Form",
    storyType: "STAFF",
    description: "For teachers, instructors, or staff members to share their experience and impact.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "title", type: "text", label: "Title/Position", placeholder: "Your title or role", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      {
        id: "background",
        type: "textarea",
        label: "Your Background",
        placeholder: "Tell us about your background and what brought you to adult education...",
        required: true,
      },
      {
        id: "role",
        type: "textarea",
        label: "Your Role & Responsibilities",
        placeholder: "What do you teach or what is your role? What programs do you work with?",
        required: true,
      },
      {
        id: "impact",
        type: "textarea",
        label: "Student Impact",
        placeholder: "Share a story about how you've impacted students or seen them succeed...",
        required: false,
      },
      {
        id: "rewarding",
        type: "textarea",
        label: "Most Rewarding Aspects",
        placeholder: "What do you find most rewarding about working in adult education?",
        required: false,
      },
      {
        id: "future",
        type: "textarea",
        label: "Vision for the Future",
        placeholder: "What are your goals for your students and program?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
  {
    id: "template_partner",
    name: "Key Partnership Form",
    storyType: "PARTNER",
    description: "For partner organizations or consortium members to share collaboration details.",
    fields: [
      { id: "name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
      { id: "title", type: "text", label: "Title/Position", placeholder: "Your title", required: true },
      { id: "organization", type: "text", label: "Organization Name", placeholder: "Your organization", required: true },
      { id: "email", type: "email", label: "Contact Email", placeholder: "email@example.com", required: true },
      { id: "phone", type: "tel", label: "Contact Phone", placeholder: "(555) 123-4567", required: true },
      { id: "city", type: "text", label: "City, State", placeholder: "City, State", required: true },
      {
        id: "partnershipType",
        type: "textarea",
        label: "Type of Partnership",
        placeholder: "Describe your partnership or collaboration with the institution...",
        required: true,
      },
      {
        id: "goals",
        type: "textarea",
        label: "Shared Goals",
        placeholder: "What are the shared goals of this partnership?",
        required: true,
      },
      {
        id: "impact",
        type: "textarea",
        label: "Community Impact",
        placeholder: "How does this partnership benefit students and the community?",
        required: false,
      },
      {
        id: "success",
        type: "textarea",
        label: "Success Stories",
        placeholder: "Share any success stories or achievements from this partnership...",
        required: false,
      },
      {
        id: "future",
        type: "textarea",
        label: "Future Plans",
        placeholder: "What are your plans for expanding or continuing this partnership?",
        required: false,
      },
      {
        id: "photoApproval",
        type: "select",
        label: "Photo Permission",
        required: true,
        options: ["Yes - I approve photos", "No - Please no photos"],
      },
      {
        id: "photoUpload",
        type: "file",
        label: "Upload a Photo (optional)",
        placeholder: "",
        required: false,
      },
    ],
  },
];

export function getReferenceTemplateById(templateId: string) {
  return referenceIntakeTemplates.find((template) => template.id === templateId) ?? null;
}
